"""empty message

Revision ID: 0e10c13eb258
Revises: 5804b8da94e3
Create Date: 2018-07-04 17:34:01.764225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e10c13eb258'
down_revision = '5804b8da94e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eo_api_env',
    sa.Column('envID', sa.Integer(), nullable=False),
    sa.Column('envName', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('envID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eo_api_env')
    # ### end Alembic commands ###
