"""empty message

Revision ID: 35d32350efea
Revises: 0e10c13eb258
Create Date: 2018-07-04 17:38:26.891895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d32350efea'
down_revision = '0e10c13eb258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eo_api_env', sa.Column('pid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'eo_api_env', 'eo_project', ['pid'], ['projectID'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'eo_api_env', type_='foreignkey')
    op.drop_column('eo_api_env', 'pid')
    # ### end Alembic commands ###
