"""empty message

Revision ID: 3f8b56051a71
Revises: 92977d1c1722
Create Date: 2018-07-02 16:43:25.207981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f8b56051a71'
down_revision = '92977d1c1722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eo_project', 'projectCreateTime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eo_project', sa.Column('projectCreateTime', mysql.DATETIME(), nullable=False))
    # ### end Alembic commands ###
