"""empty message

Revision ID: 485c025529b8
Revises: 3f8b56051a71
Create Date: 2018-07-02 17:27:22.171026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '485c025529b8'
down_revision = '3f8b56051a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eo_project', sa.Column('projectCreateTime', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eo_project', 'projectCreateTime')
    # ### end Alembic commands ###
