"""empty message

Revision ID: 5804b8da94e3
Revises: d430e4c4a043
Create Date: 2018-07-04 17:05:33.317499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5804b8da94e3'
down_revision = 'd430e4c4a043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eo_api_env', 'projectID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eo_api_env', sa.Column('projectID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
