"""empty message

Revision ID: 7d56b1fd3b43
Revises: 10c6b85c20bf
Create Date: 2018-07-05 15:37:38.019914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d56b1fd3b43'
down_revision = '10c6b85c20bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eo_api_env_param', sa.Column('paramDesc', sa.String(length=255), nullable=True))
    op.add_column('eo_api_env_param_additional', sa.Column('paramDesc', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eo_api_env_param_additional', 'paramDesc')
    op.drop_column('eo_api_env_param', 'paramDesc')
    # ### end Alembic commands ###
