"""empty message

Revision ID: 9228aec0e8d4
Revises: d5bdd36ff3d8
Create Date: 2018-07-04 20:32:59.020176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9228aec0e8d4'
down_revision = 'd5bdd36ff3d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eo_api_env', sa.Column('envDesc', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eo_api_env', 'envDesc')
    # ### end Alembic commands ###
