"""empty message

Revision ID: 92977d1c1722
Revises: dfcba585be61
Create Date: 2018-07-02 16:24:30.413907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92977d1c1722'
down_revision = 'dfcba585be61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eo_project', sa.Column('projectCreateTime', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eo_project', 'projectCreateTime')
    # ### end Alembic commands ###
