"""empty message

Revision ID: d430e4c4a043
Revises: bad73e8d0894
Create Date: 2018-07-04 17:04:03.811668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd430e4c4a043'
down_revision = 'bad73e8d0894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eo_api_env', sa.Column('projectID', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eo_api_env', 'projectID')
    # ### end Alembic commands ###
