"""empty message

Revision ID: d7dbbeccf87c
Revises: 9228aec0e8d4
Create Date: 2018-07-04 20:54:13.962890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7dbbeccf87c'
down_revision = '9228aec0e8d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eo_api_env_front_uri',
    sa.Column('uriID', sa.Integer(), nullable=False),
    sa.Column('uri', sa.String(length=255), nullable=False),
    sa.Column('applyProtocol', sa.String(length=4), nullable=True),
    sa.Column('envID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['envID'], ['eo_api_env.envID'], ),
    sa.PrimaryKeyConstraint('uriID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eo_api_env_front_uri')
    # ### end Alembic commands ###
