"""empty message

Revision ID: e8a7b0a46082
Revises: 49b39f07087e
Create Date: 2018-07-04 21:48:07.355408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8a7b0a46082'
down_revision = '49b39f07087e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eo_api_env_header',
    sa.Column('headerID', sa.Integer(), nullable=False),
    sa.Column('headerName', sa.String(length=255), nullable=False),
    sa.Column('headerValue', sa.String(length=255), nullable=False),
    sa.Column('envID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['envID'], ['eo_api_env.envID'], ),
    sa.PrimaryKeyConstraint('headerID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eo_api_env_header')
    # ### end Alembic commands ###
